### PR TITLE
Enhance with semantic HTML5

### PR DESCRIPTION
**Pull request by Zearin**
**This needs to be properly tested!** 

I have barely used Perl, and even then…
- only ≈10–12 years ago,
- in an intro classroom environment, and 
- not on a web server

That said, I tried to be careful with these changes, and I’m pretty sure everything _should_ work out fine.

If it works, this will sprinkle a dash of modern markup into things. As a nice side effect, grouping each checked URL in its own `section` will make scraping or DOM-manipulating a long results list (an inevitability with recursive link checking) a little bit easier.

### CODE REVIEW

**Comment by halindrome** [comment]
I write Perl every day - do you want me to check it?

**Comment by Zearin** [comment]
@halindrome Absolutely! Have it it :) 👍

**Comment by Zearin** [comment]
@halindrome Is it working okay?

**Comment by Zearin** [comment]
> I write Perl every day - do you want me to check it?

@halindrome I take it work has got in the way? No worries. 

If you change your mind, it's probably a very simple review for someone who knows Perl. 

If not: Anyone else who knows #perl willing to review this PR?

**Comment by dontcallmedom** [comment]
@Zearin you marked this PR as draft - is it now ready to be merged from your perspective?

**Comment by Zearin** [comment]
@dontcallmedom If it works as intended, go for it!

**Pull request merged**
